### ISSUE TITLE
No longer functioning

### ISSUE THREAD

**Issue by bookerbolin** [maciejsaw/webflow-advanced-keyboard-shortcuts#2]
Tried this bookmarklet again but doesn't seem to be working! I also copy/pasted into the console and got the "jQuery Hotkeys loaded" success message, but "shift+alt" doesn't move focus to the class field.

**Comment by maciejsaw** [comment]
Thanks for informing me. Looks like Webflow made a major update to the UI and I need to update the script. I'll look into this.

**Comment by maciejsaw** [comment]
Fixed it, try and let me know if it works.
Note that you need to hold the shift+alt a fraction of second longer than usually, because Webflow changed something and now "alt" closes the css class focus.

**Comment by bookerbolin** [comment]
Bookmarklet doesn't work... should I try pasting the code in console?

**Comment by maciejsaw** [comment]
You need to recreate the bookmarklet to make it work again. 
In the meantime I'm working on Grasemonkey script so that we won't have to remember to init this and it will be initiated automatically.

**Comment by bookerbolin** [comment]
Works again! Thanks 👍🏽
